{
 "title": "orders Logs (Loki)",
 "tags": [
  "orders",
  "loki",
  "lab07"
 ],
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "route",
    "query": "label_values({namespace=\"orders\", app=\"orders\"}, route)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrique - debit HTTP par route (Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_requests_total{app=\"orders\"}[5m]))"
    }
   ]
  },
  {
   "title": "Metrique - ratio erreurs 5xx (Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=\"orders\",status=~\"5..\"}[5m])) / sum(rate(http_requests_total{app=\"orders\"}[5m]))"
    }
   ]
  },
  {
   "title": "Logs - toutes les requetes orders",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"orders\", app=\"orders\"} | json | event=\"request_completed\""
    }
   ]
  },
  {
   "title": "Logs - erreurs et scenarios d'alerte",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"orders\", app=\"orders\"} | json | levelname=~\"WARNING|ERROR\" or event=\"alert_scenario_triggered\""
    }
   ]
  },
  {
   "title": "Logs - filtre par route (LogQL)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{namespace=\"orders\", app=\"orders\", route=~\"$route\"} | json"
    }
   ]
  }
 ]
}